version: 0.0
os: linux
version: 0.0
os: linux
files:
  -source: /
   destination: /home/ec2-user/simple-nodejs-app
hooks:
  AfterInstall:
    -location: deploy/after_install.sh
     timeout: 300
 ApplicationStart:
   -location: deploy/application_start.sh
    timeout: 300
