version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo Installing source node dependencies.....
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the node code
  post_build:
    commmands:
      - echo Build completed on `date`
